datapipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      dbname: ecommerce
      user: pipeline_user
      password: pipeline_pass
      schema: public
      threads: 4
