datapipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: db.vjdfcormtplscencxggn.supabase.co
      port: 5432
      dbname: postgres
      user: postgres
      password: databasepipeline0880
      schema: public
      threads: 4
      sslmode: require
